version: '5.0'
services:
  web:
    build:
      context: ./
      target: RUN
    volumes:
      - .:/app
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
